"""initial

Revision ID: f05df153395f
Revises:
Create Date: 2026-01-13 21:34:58.891078

"""

from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f05df153395f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_interests_name"), "interests", ["name"], unique=False)
    op.create_index(op.f("ix_interests_user_id"), "interests", ["user_id"], unique=False)
    op.create_table(
        "newsletters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_newsletters_user_id"), "newsletters", ["user_id"], unique=False)
    op.create_table(
        "content_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("newsletter_id", sa.Integer(), nullable=False),
        sa.Column("interest", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["newsletter_id"], ["newsletters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_items_interest"), "content_items", ["interest"], unique=False)
    op.create_index(
        op.f("ix_content_items_newsletter_id"), "content_items", ["newsletter_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_items_source_url"), "content_items", ["source_url"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_items_source_url"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_newsletter_id"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_interest"), table_name="content_items")
    op.drop_table("content_items")
    op.drop_index(op.f("ix_newsletters_user_id"), table_name="newsletters")
    op.drop_table("newsletters")
    op.drop_index(op.f("ix_interests_user_id"), table_name="interests")
    op.drop_index(op.f("ix_interests_name"), table_name="interests")
    op.drop_table("interests")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
